name: veracode-build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package source for Veracode
        run: |
          zip -r app.zip . -x ".git/*" "node_modules/*" ".github/*"

      - name: Upload artifact for Veracode
        uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: app.zip
