name: veracode-build

on:
  repository_dispatch:
    types: [veracode-build]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Package source
        run: zip -r app.zip . -x ".git/*" "node_modules/*" ".github/*"

      - uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: app.zip
